name: Docker Image CI
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build indico Docker image
      run: ./build_latest.sh
